INSERT INTO role (id, role) VALUES (1, 'Administrateur');
INSERT INTO role (id, role) VALUES (2, 'Abonne');
INSERT INTO role (id, role) VALUES (3, 'Visiteur');
INSERT INTO role (id, role) VALUES (4, 'Employe');
INSERT INTO utilisateur(id, email, nom, prenom, password, role_id) VALUES(1, 'ADMIN@OC.COM','ADMIN', 'ADMIN', '$2a$11$NWK4enrvaXbcLu0Hf4eVIe3cdNk82VO6BvfNx7UMBeHYGJjQcFMQi', '1');
INSERT INTO utilisateur(id, email, nom, prenom, password, role_id) VALUES(2, 'USER@OC.COM', 'USER', 'USER', '$2a$11$fwbi72Ko53c6Dvd87f7d7u7hkiFQ5dGnS2SO8JYdiMO41olj78EQi', '3');
INSERT INTO utilisateur(id, email, nom, prenom, password, role_id) VALUES(3, 'MEMBRE@OC.COM', 'MEMBRE', 'MEMBRE', '$2a$11$yel.cNbeeJNTEa7czcLHHup4wIJVQLqay293LmAewxQZgSV05KSAK', '2');
INSERT INTO utilisateur(id, email, nom, prenom, password, role_id) VALUES(4, 'GLESCROEL@HOTMAIL.COM', 'LESCROEL', 'Gregory', '$2a$11$NWK4enrvaXbcLu0Hf4eVIe3cdNk82VO6BvfNx7UMBeHYGJjQcFMQi', '1');
INSERT INTO utilisateur(id, email, nom, password, prenom, role_id) VALUES (5, 'DUPONT@OC.COM', 'DUPONT', '$2a$11$poeYMQ8pqjKSk1GqvidW2./pYd6kVly0iVrwKB8uWd/YBJocoUOci', 'RENÉ', 3);
INSERT INTO utilisateur(id, email, nom, password, prenom, role_id) VALUES (6, 'DUBOIS@OC.COM', 'DUBOIS', '$2a$11$2LLBNGe2bzp1YUsAA7T/RuXmzK7ascvDammvpgsN10bUwOH3LQi7O', 'ANDRÉE', 3);
INSERT INTO utilisateur(id, email, nom, password, prenom, role_id) VALUES (7, 'SMITH@OC.COM', 'SMITH', '$2a$11$doPqn9Ex3T9zKrjm3R09m.LnjbeEMNGKWwwR2ElBcevmvaPi9uQ32', 'JOHN', 3);
INSERT INTO ouvrage(id, titre, resume) VALUES (1, 'Les 30 plus belles histoires pour les tout-petits', 'Un recueil d"histoires merveilleuses pour nos tout petits');
INSERT INTO ouvrage(id, titre, resume) VALUES (2, 'Les plus belles histoires pour les enfants de 2 ans', 'Un recueil d"histoires merveilleuses pour les enfants de 2 ans');
INSERT INTO ouvrage(id, titre, resume) VALUES (3, 'Les plus belles histoires pour les enfants de 3 ans', 'Un recueil d"histoires merveilleuses pour les enfants de 3 ans');
INSERT INTO ouvrage(id, titre, resume) VALUES (4, 'Les plus belles histoires pour les enfants de 4 ans', 'Un recueil d"histoires merveilleuses pour les enfants de 4 ans');
INSERT INTO ouvrage(id, titre, resume) VALUES (5, 'Les plus belles histoires pour les enfants de 5 ans', 'Un recueil d"histoires merveilleuses pour les enfants de 5 ans');
INSERT INTO ouvrage(id, titre, resume) VALUES (6, 'Les plus belles histoires pour les enfants de 6 ans', 'Un recueil d"histoires merveilleuses pour les enfants de 6 ans');
INSERT INTO ouvrage(id, titre, resume) VALUES (7, 'Les plus belles histoires de fées et de princesses', 'Un recueil d"histoires merveilleuses pleines de fées, de princesses mais aussi de sorcières et de dragons');
INSERT INTO ouvrage(id, titre, resume) VALUES (8, 'Les plus belles histoires du Prince de Motordu', 'Une compilation des meilleures aventures du Prince de Motordu');
INSERT INTO ouvrage(id, titre, resume) VALUES (9, 'Je veux une histoire !', 'Une compilation des meilleures histoires d"une petite Princesse facétieuse');
INSERT INTO ouvrage(id, titre, resume) VALUES (10, 'Les plus belles histoires pour l"école maternelle', 'Un recueil d"histoires merveilleuses pour les enfants en école maternelle');
INSERT INTO ouvrage(id, titre, resume) VALUES (11, 'Les 25 plus belles histoires de noël', 'Un recueil d"histoires de noël merveilleuses');
INSERT INTO ouvrage(id, titre, resume) VALUES (12, 'Les 20 plus belles histoires à lire le soir', 'Un recueil d"histoires merveilleuses à lire au coucher pour aider les enfants à faire de beaux rêves');
INSERT INTO ouvrage(id, titre, resume) VALUES (13, 'Les lettres de mon moulin', 'Un recueil de nouvelles champêtres d"Alphonse Daudet');
