INSERT INTO role (id, role) VALUES (1, 'Administrateur');
INSERT INTO role (id, role) VALUES (2, 'Abonne');
INSERT INTO role (id, role) VALUES (3, 'Visiteur');
INSERT INTO role (id, role) VALUES (4, 'Employe');
INSERT INTO UTILISATEUR(id, email, nom, prenom, password, role_id) VALUES(1, 'ADMIN@OC.COM','ADMIN', 'ADMIN', '$2a$11$NWK4enrvaXbcLu0Hf4eVIe3cdNk82VO6BvfNx7UMBeHYGJjQcFMQi', '1');
INSERT INTO UTILISATEUR(id, email, nom, prenom, password, role_id) VALUES(2, 'USER@OC.COM', 'USER', 'USER', '$2a$11$fwbi72Ko53c6Dvd87f7d7u7hkiFQ5dGnS2SO8JYdiMO41olj78EQi', '3');
INSERT INTO UTILISATEUR(id, email, nom, prenom, password, role_id) VALUES(3, 'MEMBRE@OC.COM', 'MEMBRE', 'MEMBRE', '$2a$11$yel.cNbeeJNTEa7czcLHHup4wIJVQLqay293LmAewxQZgSV05KSAK', '2');
INSERT INTO UTILISATEUR(id, email, nom, prenom, password, role_id) VALUES(4, 'GLESCROEL@HOTMAIL.COM', 'LESCROEL', 'Gregory', '$2a$11$NWK4enrvaXbcLu0Hf4eVIe3cdNk82VO6BvfNx7UMBeHYGJjQcFMQi', '1');
INSERT INTO utilisateur (id, email, nom, password, prenom, role_id) VALUES (5, 'DUPONT@OC.COM', 'DUPONT', '$2a$11$poeYMQ8pqjKSk1GqvidW2./pYd6kVly0iVrwKB8uWd/YBJocoUOci', 'RENÉ', 3);
INSERT INTO utilisateur (id, email, nom, password, prenom, role_id) VALUES (6, 'DUBOIS@OC.COM', 'DUBOIS', '$2a$11$2LLBNGe2bzp1YUsAA7T/RuXmzK7ascvDammvpgsN10bUwOH3LQi7O', 'ANDRÉE', 3);
INSERT INTO utilisateur (id, email, nom, password, prenom, role_id) VALUES (7, 'SMITH@OC.COM', 'SMITH', '$2a$11$doPqn9Ex3T9zKrjm3R09m.LnjbeEMNGKWwwR2ElBcevmvaPi9uQ32', 'JOHN', 3);
